---
- hosts: utility
  vars:
    var_ambari_user: admin
    var_ambari_password: admin
  tasks:
  # list registered cluster hosts
  - uri:
      url: "http://{{ lookup('file', 'ambariserver.txt') }}:8080/api/v1/hosts"
      method: GET
      HEADER_Content-Type: application/json
      return_content: yes
      user: "{{ var_ambari_user }}"
      password: "{{ var_ambari_password }}" 
      force_basic_auth: yes
    register: resp_hosts
  - debug: msg="{{ (resp_hosts.content|from_json)['items'].0['Hosts']['host_name'] }}"
