---
- hosts: utility
  vars:
    var_ambari_user: admin
    var_ambari_password: admin
  tasks:
  # list registered cluster hosts
  - uri:
      url: "http://{{ lookup('file', 'ambariserver.txt') }}:8080/api/v1/hosts"
      method: GET
      HEADER_X-Requested_by: Pythian
      HEADER_Content-Type: application/json
      return_content: yes
      user: "{{ var_ambari_user }}"
      password: "{{ var_ambari_password }}"
      force_basic_auth: yes
    register: resp_hosts
  - name: remove hosts.out if it exists
    file: path=/tmp/hosts.out state=absent
  - name: write the registered cluster hosts to file
    template: src=~/hostmap.tpl dest=~/hostmap.json
#
# IMPORTANT NOTE: https://github.com/ansible/ansible-modules-core/pull/1011
# REQUIRES A SPACE IN FRONT OF THE "lookup()" function in the "body:" VALUE OF THE URI MODULE - DON'T REMOVE THE SPACES!
#
  # post the blueprint and hostmap to initiate cluster build
  - uri:
      url: "http://{{ lookup('file', 'ambariserver.txt') }}:8080/api/v1/blueprints/testclus"
      method: POST
      HEADER_X-Requested-By: Pythian
      HEADER_Content-Type: application/json
      user: "{{ var_ambari_user }}"
      password: "{{ var_ambari_password }}"
      force_basic_auth: yes
      body_format: json
      body: " {{ lookup('file', '~/testclus.json') }}"
  - uri:
      url: "http://{{ lookup('file', 'ambariserver.txt') }}:8080/api/v1/clusters/testclus"
      method: POST
      HEADER_X-Requested-By: Pythian
      HEADER_Content-Type: application/json
      user: "{{ var_ambari_user }}"
      password: "{{ var_ambari_password }}"
      force_basic_auth: yes
      body_format: json
      body: " {{ lookup('file', '~/testclus.json') }}"

