---
- hosts: utility
  tasks:
  # authenticate
  - action: "uri url=http://{{ lookup('file', 'ambariserver.txt') }}:8080/ method=GET return_content=yes user=admin password=admin force_basic_auth=yes"
  # list registered cluster hosts
  - action: "uri url=http://{{ lookup('file', 'ambariserver.txt') }}:8080/api/v1/hosts method=GET user=admin password=admin force_basic_auth=yes return_content=yes"
    register: response
  - debug: msg="{{  (response|from_json) }}"
