---
# Run some tasks to install dependencies
- hosts: all
  vars:
   var_remote_user: centos
   var_sudo: yes
  remote_user: "{{ var_remote_user }}"
  sudo: "{{ var_sudo }}"
  tasks:
  - name: install dependency packages (RedHat)
    yum: name={{ item }} state=present
    when: ansible_os_family == 'RedHat'
    with_items:
      - zip
      - unzip
      - wget
      - sysstat
      - ntp
      - telnet
  - name: configure ntp (Redhat)
    service: name=ntpd enabled=yes state=restarted
    when: ansible_os_family == 'RedHat'    

