---
# Run some tasks to install dependencies
- hosts: all
  vars:
   var_remote_user: centos
   var_sudo: yes
  remote_user: "{{ var_remote_user }}"
  sudo: "{{ var_sudo }}"
  tasks:
  - name: install dependency packages (RedHat)
    when: ansible_os_family == 'RedHat'
    yum: name={{ item }} state=present
    with_items:
      - zip
      - unzip
      - wget
      - sysstat
      - ntp
      - telnet
  - name: fetch java rpm (Redhat)
    when: ansible_os_family == 'RedHat'
    command:  wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jre-8u65-linux-x64.rpm
  - name: install java runtime environment (RedHat)
    when: ansible_os_family == 'RedHat'
    yum: name=jre-8u65-linux-x64.rpm state=present
  - name: configure ntp (Redhat)
    when: ansible_os_family == 'RedHat'
    service: name=ntpd enabled=yes state=restarted

